dataset_kwargs:
  data_files: /Users/yuwu/PycharmProjects/FATE-LLM/python/fate_llm/evaluate/tasks/dolly_15k/databricks-dolly-15k-short.jsonl
dataset_path: json
doc_to_target: '{{response}}'
doc_to_text: !function 'dolly_utils.doc_to_text'
metric_list:
- aggregation: mean
  higher_is_better: true
  metric: !function 'dolly_utils.rouge_l'
output_type: generate_until
task: dolly-15k
validation_split: train
